// Temporary mock data — replace with API call when backend is ready

export const products = [
	{
		id: 'spring-elegance',
		title: 'Spring Elegance',
		price: '$35',
		image: './images/original/spring-elegance.jpg',
		alt: 'Spring Elegance bouquet — a woman holding a beautiful spring flower bouquet',
		description: 'Each stem is carefully selected to create a bouquet that radiates freshness, elegance, and the gentle charm of spring. Whether you\'re celebrating a birthday, sending love, or simply brightening someone\'s day, this arrangement is sure to bring warm smiles and lasting impressions.',
	},
	{
		id: 'berry-chic',
		title: 'Berry Chic',
		price: '$40',
		image: './images/original/berry-chic.jpg',
		alt: 'Berry Chic bouquet — bridal arrangement with roses and berries',
		description: 'A stylish composition of roses, seasonal greenery, and vibrant berries — a bold and elegant floral statement that is perfect for special occasions and thoughtful gifts alike.',
	},
	{
		id: 'lavender-dream',
		title: 'Lavender Dream',
		price: '$55',
		image: './images/original/lavender-dream.jpg',
		alt: 'Lavender Dream bouquet — mixed flowers on a wooden table',
		description: 'A rich bouquet with lavender, lisianthus, and roses — ideal for those who love deep hues and gentle fragrance. This arrangement evokes a sense of calm elegance and timeless beauty.',
	},
	{
		id: 'peach-meadow',
		title: 'Peach Meadow',
		price: '$55',
		image: './images/original/peach-meadow.jpg',
		alt: 'Peach Meadow — soft arrangement of peach and blush roses in a straw basket',
		description: 'A soft and radiant arrangement of peach and blush roses with lush greenery in a straw basket. Light, natural, and full of warmth — perfect for gifting someone you cherish on any occasion.',
	},
	{
		id: 'blush-romance',
		title: 'Blush Romance',
		price: '$34',
		image: './images/original/blush-romance.jpg',
		alt: 'Blush Romance — deep pink and ivory roses with silver eucalyptus',
		description: 'A premium bouquet of deep pink and ivory roses, complemented by silver eucalyptus. Sophisticated and intimate, this arrangement is a timeless expression of love and admiration for any special moment.',
	},
	{
		id: 'pastel-garden',
		title: 'Pastel Garden',
		price: '$40',
		image: './images/original/pastel-garden.jpg',
		alt: 'Pastel Garden — pastel-toned spray roses and greenery in a woven basket',
		description: 'A pastel-toned mix of spray roses and greenery arranged in a woven basket. Gentle, airy, and perfect for any occasion — this bouquet brings a quiet, effortless joy that lifts the spirit and brightens any room.',
	},
	{
		id: 'tulip-charm',
		title: 'Tulip Charm',
		price: '$61',
		image: './images/original/tulip-charm.jpg',
		alt: 'Tulip Charm — bright tulips and roses in a lavender box',
		description: 'A vivid bouquet of bright tulips and roses presented in a lovely lavender box. Cheerful and full of charm, this arrangement is perfect for birthdays, celebrations, or simply making someone\'s day unforgettable.',
	},
	{
		id: 'berry-bloom',
		title: 'Berry Bloom',
		price: '$32',
		image: './images/original/berry-bloom.jpg',
		alt: 'Berry Bloom — rich pink, purple, and cream blooms with textured greens',
		description: 'A lush mix of rich pink, purple, and cream blooms with textured greens. Romantic and elegant, Berry Bloom is the perfect statement bouquet for those who appreciate bold floral compositions and want to make a lasting impression.',
	},
	{
		id: 'sweet-whisper',
		title: 'Sweet Whisper',
		price: '$40',
		image: './images/original/sweet-whisper.jpg',
		alt: 'Sweet Whisper — spring bouquet with peonies, roses and lilac accents',
		description: 'A charming spring bouquet with peonies, roses, and lilac-toned accents. Fresh, lively, and expressive — Sweet Whisper captures the feeling of a warm spring morning and is perfect for moments that deserve something truly special.',
	},
	{
		id: 'field-joy',
		title: 'Field Joy',
		price: '$49',
		image: './images/original/field-joy.jpg',
		alt: 'Field Joy — rustic bouquet of sunflowers, lisianthus and daisies',
		description: 'A rustic hand-tied bouquet of sunflowers, lisianthus, and daisies. Perfect for brightening the day, Field Joy brings the carefree spirit of open fields and golden afternoons into any space with its warm, natural energy.',
	},
	{
		id: 'soft-bloom',
		title: 'Soft Bloom',
		price: '$37',
		image: './images/original/soft-bloom.jpg',
		alt: 'Soft Bloom — pink carnations and roses wrapped in satin paper',
		description: 'A delicate bouquet of pink carnations and roses wrapped in satin paper. Soft, stylish, and versatile — Soft Bloom is a heartfelt gift for any moment, from everyday appreciation to milestone celebrations worth remembering.',
	},
];
